/**
 * Мок-данные сценариев для таблицы «Все сценарии»
 */

export const scenarios = [
  {
    id: 1,
    name: 'Вход в сервис Витрина',
    description: '',
    status: 'draft',
    statusLabel: 'Черновик',
    author: 'Кирилл Митюшин',
    authorInitials: 'КМ',
    authorColor: '#95AEE2',
    date: '12.08.2025',
  },
  {
    id: 2,
    name: 'Продвижение ДМС',
    description: 'Триггер при просмотре страницы зарплатных продуктов более 30 секунд',
    status: 'published',
    statusLabel: 'Опубликован',
    author: 'Кирилл Митюшин',
    authorInitials: 'КМ',
    authorColor: '#95AEE2',
    date: '22.10.2025',
  },
  {
    id: 3,
    name: 'Тест в неработе',
    description: 'Проверка отображения баннера при неактивном статусе клиента',
    status: 'started',
    statusLabel: 'Запущен',
    author: 'Вадим Артёменко',
    authorInitials: 'ВА',
    authorColor: '#82C9A1',
    date: '02.03.2025',
  },
  {
    id: 4,
    name: 'Бенну. Переход на вкладку ИИ-ассистента в личном кабинете корпоративного клиента',
    description: 'ai-support-a — показ подсказки при первом переходе в раздел ИИ-ассистента с автоматическим определением типа устройства и адаптацией интерфейса под мобильную и десктопную версии',
    status: 'stopped',
    statusLabel: 'Остановлен',
    author: 'Антон Елькин',
    authorInitials: 'АЕ',
    authorColor: '#C799DF',
    date: '01.10.2025',
  },
  {
    id: 5,
    name: 'Показ плашки об обновлении страницы в Blink',
    description: '',
    status: 'finishing',
    statusLabel: 'Завершает работу',
    author: 'Кирилл Митюшин',
    authorInitials: 'КМ',
    authorColor: '#95AEE2',
    date: '12.08.2025',
  },
  {
    id: 6,
    name: 'Тест чекаут кабинет',
    description: 'common__view-page, params: {"label":"/orders"}',
    status: 'draft',
    statusLabel: 'Черновик',
    author: 'Антон Елькин',
    authorInitials: 'АЕ',
    authorColor: '#C799DF',
    date: '22.10.2025',
  },
  {
    id: 7,
    name: 'Онбординг нового пользователя',
    description: 'Показ приветственного тура при первом входе в личный кабинет',
    status: 'published',
    statusLabel: 'Опубликован',
    author: 'Мария Соколова',
    authorInitials: 'МС',
    authorColor: '#F2A365',
    date: '05.11.2025',
  },
  {
    id: 8,
    name: 'Уведомление о просроченной задаче в проектном трекере бизнес-подразделения',
    description: 'Отправка push-уведомления при истечении дедлайна задачи в проекте с дублированием на электронную почту руководителя подразделения и автоматическим переносом срока на следующий рабочий день',
    status: 'started',
    statusLabel: 'Запущен',
    author: 'Вадим Артёменко',
    authorInitials: 'ВА',
    authorColor: '#82C9A1',
    date: '17.09.2025',
  },
  {
    id: 9,
    name: 'A/B тест кнопки «Оформить карту»',
    description: 'Сравнение конверсии двух вариантов CTA на главной странице',
    status: 'started',
    statusLabel: 'Запущен',
    author: 'Дмитрий Волков',
    authorInitials: 'ДВ',
    authorColor: '#E8959A',
    date: '30.07.2025',
  },
  {
    id: 10,
    name: 'Ретаргетинг брошенных заявок',
    description: 'Повторный показ формы заявки клиентам, не завершившим оформление',
    status: 'published',
    statusLabel: 'Опубликован',
    author: 'Мария Соколова',
    authorInitials: 'МС',
    authorColor: '#F2A365',
    date: '14.06.2025',
  },
  {
    id: 11,
    name: 'Кросс-продажа РКО после открытия счёта',
    description: '',
    status: 'draft',
    statusLabel: 'Черновик',
    author: 'Дмитрий Волков',
    authorInitials: 'ДВ',
    authorColor: '#E8959A',
    date: '28.11.2025',
  },
  {
    id: 12,
    name: 'Напоминание об окончании подписки на тарифный план с автоматическим предложением продления',
    description: 'Отправка email за 7 и 3 дня до окончания подписки на тариф «Бизнес» с персонализированным предложением скидки при продлении на год и ссылкой на сравнение тарифных планов',
    status: 'stopped',
    statusLabel: 'Остановлен',
    author: 'Антон Елькин',
    authorInitials: 'АЕ',
    authorColor: '#C799DF',
    date: '03.05.2025',
  },
  {
    id: 13,
    name: 'Промо зарплатного проекта',
    description: 'Баннер для компаний с 50+ сотрудниками без подключённого зарплатного проекта',
    status: 'finishing',
    statusLabel: 'Завершает работу',
    author: 'Мария Соколова',
    authorInitials: 'МС',
    authorColor: '#F2A365',
    date: '19.04.2025',
  },
  {
    id: 14,
    name: 'Сбор NPS после обращения в поддержку',
    description: 'Всплывающий опрос через 24 часа после закрытия обращения',
    status: 'published',
    statusLabel: 'Опубликован',
    author: 'Вадим Артёменко',
    authorInitials: 'ВА',
    authorColor: '#82C9A1',
    date: '08.12.2025',
  },
  {
    id: 15,
    name: 'Рекомендация эквайринга',
    description: 'Показ предложения при обороте по счёту более 500 000 ₽ в месяц',
    status: 'draft',
    statusLabel: 'Черновик',
    author: 'Дмитрий Волков',
    authorInitials: 'ДВ',
    authorColor: '#E8959A',
    date: '25.01.2026',
  },
]
