import React from 'react';
import {
    Circle,
    QuestionCircle,
    ChevronDown,
    Checkmark,
    Minus,
    AcquiringAcsRuble,
    Acquiring,
    AirplanePaperRight,
    AirplaneRight,
    Amber,
    AppIconTSquare,
    ArrowDown,
    ArrowDownListSortedReverse,
    ArrowDownUnderline,
    ArrowLeftDownArrowRightUp,
    ArrowLeft,
    ArrowReturnLeft,
    ArrowReturnRight,
    ArrowRight,
    ArrowRightIncomingRectangleVertical,
    ArrowRightOutgoingRectangleVertical,
    ArrowRightTopOutgoingSquare,
    ArrowRightUpArrowLeftDown,
    ArrowRotationLeft,
    ArrowRotationRight,
    ArrowsCollapse,
    ArrowsDirectionsHorizontalRectangle,
    ArrowsDirectionsVertical,
    ArrowsExpand,
    ArrowsRotationLeftDollar,
    ArrowsRotationLeftFlattened,
    ArrowsRotationLeftRuble,
    ArrowsRotationRightA,
    ArrowsRotationRight,
    ArrowsRotationRightT,
    ArrowsRotationRightYuan,
    ArrowsShuffleRight,
    ArrowTurnDownRight,
    ArrowTurnLeftDown,
    ArrowUpArrowDown,
    ArrowUp,
    ArrowUpIncomingRectangleHorizontal,
    ArrowUpListSorted,
    ArrowUpUnderline,
    BadgeListShortReverseCenter,
    BadgeRibbon,
    BadgeRoundedPercent,
    BagPercent,
    Barcode,
    BellCrossedOut,
    Bell,
    Book,
    BookmarkCrossedOut,
    Bookmark,
    Bookmarks,
    BookShadow,
    BottleBaby,
    BoxArrowUp,
    Box,
    BoxPartition,
    Broom,
    BubbleListShort,
    BubblesRounded,
    BuildingBank,
    BuildingGovernment,
    CalendarAcsA,
    CalendarAcsArrowRotationRight,
    Calendar,
    CardAcsArrowLeftIncoming,
    CardAcsArrowRightIncoming,
    CardAcsArrowRightOutgoing,
    CardAcsCross,
    CardAcsPlus,
    CardCrossedOut,
    Card,
    Cards,
    Car,
    Chain,
    ChartBar,
    ChartSector,
    ChatGPT,
    Checkmarks,
    ChevronLeft,
    ChevronRight,
    ChevronsLeft,
    ChevronsRight,
    ChevronUp,
    Clip,
    CloudArrowDownOutgoing,
    Cloud,
    CoinsDollar,
    CoinsEuro,
    CoinsPlane,
    CoinsRuble,
    CoinsYuan,
    ColorPalette,
    Compass,
    Component,
    ConnectionArrowsRepeatLeft,
    ConnectionArrowTurnLeftDownA,
    ConnectionArrowTurnRightUpA,
    CornerRounded,
    Corners,
    CornersLine,
    Cross,
    CryptoPro,
    DocumentBookList,
    DocumentListAcsArrowDownOutgoing,
    DocumentListAcsArrowRightOutgoing,
    DocumentListAcsArrowRotationRight,
    DocumentListAcsCross,
    DocumentListAcsMagnifier,
    DocumentListAcsPlus,
    DocumentListAcsShield,
    DocumentListAcsStar,
    DocumentListBulletedAcsArrowRightIncoming,
    DocumentListBulletedAcsCross,
    DocumentListBulletedAcsPlus,
    DocumentListBulleted,
    DocumentList,
    DocumentListMedicine,
    DocumentLosses,
    DocumentPatent,
    DocumentPercentAcsWatch,
    DocumentProfile,
    DocumentReportAcsArrowRightOutgoing,
    DocumentReportAcsPlus,
    DocumentReport,
    Done,
    DotsThreeHorizontalArrowDownOutgoing,
    DotsThreeHorizontal,
    DotsThreeVertical,
    DropPlus,
    Earth,
    EmblemCross,
    EmblemListShortCenter,
    EmblemPercent,
    EmblemProfile,
    EmblemTAcsCross,
    EmblemT,
    Envelope,
    Exit,
    EyeAcsPlus,
    EyeClosed,
    Eye,
    FaceAuthentication,
    FaceHappy,
    FaceNeutral,
    FaceNeutralSquare,
    FaceUnhappy,
    FAQQuestion,
    FileAcsArrowLeftOutgoing,
    FileAcsCoins,
    FileAcsHouse,
    FileAcsMagnifier,
    FileAcsPencil,
    FileAcsPen,
    FileAcsPlus,
    FileAnalysis,
    FileArrowReturnUp,
    FileElasticBand,
    File,
    FileListShortReverseAcsArrowRightOutgoing,
    FileListShortReverseAcsCalendar,
    FileListShortReverseAcsChartBar,
    FileListShortReverseAcsCoinsPlane,
    FileListShortReverseAcsCross,
    FileListShortReverseAcsLock,
    FileListShortReverseAcsPencil,
    FileListShortReverseAcsPercent,
    FileListShortReverseAcsWatch,
    FileListShortReverseAcsYuan,
    FileListShortReverse,
    FileListShortReverseMapAcsPin,
    FileOdinS,
    Filters,
    Fingerprint,
    Flag,
    Gavel,
    Gear,
    Gift,
    Globe,
    Goblet,
    Hand,
    HatGlasses,
    Headphones,
    Heart,
    HeartPulse,
    HeartT,
    House,
    HousePercentCrossedOut,
    HousePercent,
    Integration,
    KeyAcsWatch,
    KeyboardKeyBackspaceCross,
    KeyboardKeyT,
    Key,
    Kiosk,
    LaptopAcsPhone,
    Laptop,
    LaptopT,
    LayerOnLayerRectangleVerticalAngled,
    LayerOnLayerRectangleVertical,
    LayoutGrid,
    LayoutRowsTwo,
    LayoutSquaresFour,
    LayoutSquaresFourRhombusOne,
    LayoutStackVerticalRounded,
    LetterAAcsStarShine,
    LetterACursor,
    LetterB,
    LetterBRusAcsStarShine,
    LetterIItalic,
    LettersAAUnderline,
    LetterSCrossedOut,
    LettersHieroglyphA,
    LetterUUnderline,
    LetterY,
    LightBulb,
    Lightning,
    LinesThreeHorizontal,
    LinesThreeHorizontalWide,
    ListBulleted,
    ListBulletedMultiline,
    ListChecked,
    ListNumberedOneTwo,
    ListSortedCenter,
    ListSortedReverseCenter,
    ListUnchecked,
    Lock,
    LockOpen,
    MagicStick,
    Magnifier,
    MagnifierPlus,
    MailDog,
    MapCurrentLocation,
    Map,
    MapPin,
    Megaphone,
    Microphone,
    MoneyAcceptorArrowDown,
    MoneyAcceptorArrowUp,
    Moneybox,
    MoonStarShine,
    Network,
    Pacifier,
    Pattern,
    Pencil,
    Pen,
    Percent,
    PersonAcsArrowRightOutgoing,
    PersonAcsChain,
    PersonAcsCross,
    PersonAcsHeart,
    PersonAcsMagnifier,
    PersonAcsOdinS,
    PersonAcsPlus,
    PersonAcsQuestion,
    PersonAcsRuble,
    PersonAcsStar,
    Person,
    PersonLaptop,
    PersonMan,
    PersonMilitary,
    PersonWoman,
    PhoneHandsetArrowRightDownIncoming,
    PhoneHandsetArrowRightUpOutgoing,
    PhoneHandset,
    PhoneMobile,
    Phonendoscope,
    PhotoCamera,
    Photo,
    PlaySquare,
    Plus,
    PlusSubscriptionSquare,
    PostBox,
    PouchT,
    Power,
    Printer,
    Puzzle,
    QRCodeAcsArrowRightOutgoing,
    QRCode,
    ReceiptListShortAcsArrowRightIncoming,
    ReceiptListShortAcsPlus,
    ReceiptListShort,
    RecordSquare,
    RequisitesListShortAcsArrowRightOutgoing,
    RequisitesListShortAcsArrowRotationRight,
    RequisitesListShortAcsCross,
    RequisitesListShort,
    RequisitesT,
    ReviewAcsMagnifier,
    Rocket,
    RubleDigital,
    Safe,
    ShareAndroid,
    Share,
    ShieldLock,
    ShieldMagnifier,
    ShieldPercent,
    Shop,
    ShoppingBasket,
    SidebarChevronLeft,
    SidebarChevronRight,
    SignalHorizontal,
    SignalVertical,
    Snowflake,
    Spacing,
    SpeedometerAcsCross,
    Speedometer,
    Spravochnaya,
    StarCrossedOut,
    Star,
    SuitcaseAcsPlus,
    Suitcase,
    Sun,
    Tag,
    TargetDarts,
    Telegram,
    ThumbDown,
    ThumbUp,
    Trash,
    TruckAcsPlus,
    Truck,
    Umbrella,
    USBFlashDriveAcsMagnifier,
    USBFlashDrive,
    VectorSector,
    WalletAcsArrowDownIncoming,
    WalletAcsPlus,
    Wallet,
    WarningTriangle,
    WatchAcsTwoFour,
    WatchArrowRotationLeft,
    Watch,
    WatchTimer,
    WhatsApp,
    X,
} from '../../src/icons';
import { ChevronDown as ChevronDown12 } from '../../src/assets/Icon/12/Filled';
import { InformationCircle as InformationCircle20 } from '../../src/assets/Icon/20/Filled';

type IconItem = {
    name: string;
    displayName: string;
    icon: React.ReactNode;
    viewBox: string;
};

type IconStyle = 'Filled' | 'Stroked';

type IconGroup = {
    style: IconStyle;
    icons: IconItem[];
};

type IconSize = {
    label: string;
    size: string;
    groups: IconGroup[];
};

const ICON_SIZES: IconSize[] = [
    {
        label: '12px',
        size: '12px',
        groups: [
            {
                style: 'Filled',
                icons: [
                    { name: 'ChevronDown', displayName: 'ChevronDown', icon: <ChevronDown12 />, viewBox: '0 0 12 12' }
                ]
            }
        ]
    },
    {
        label: '16px',
        size: '16px',
        groups: [
            {
                style: 'Stroked',
                icons: [
                    { name: 'Checkmark', displayName: 'Checkmark', icon: <Checkmark />, viewBox: '0 0 16 16' },
                    { name: 'Minus', displayName: 'Minus', icon: <Minus />, viewBox: '0 0 16 16' }
                ]
            }
        ]
    },
    {
        label: '20px',
        size: '20px',
        groups: [
            {
                style: 'Filled',
                icons: [
                    { name: 'InformationCircle', displayName: 'InformationCircle', icon: <InformationCircle20 />, viewBox: '0 0 20 20' },
                ]
            },
            {
                style: 'Stroked',
                icons: [
                    { name: 'QuestionCircle', displayName: 'QuestionCircle', icon: <QuestionCircle />, viewBox: '0 0 20 20' },
                ]
            }
        ]
    }
];

const NEW_ICONS: IconItem[] = [
    { name: 'Circle', displayName: 'Circle', icon: <Circle />, viewBox: '0 0 24 24' },
    { name: 'AcquiringAcsRuble', displayName: 'AcquiringAcsRuble', icon: <AcquiringAcsRuble />, viewBox: '0 0 24 24' },
    { name: 'Acquiring', displayName: 'Acquiring', icon: <Acquiring />, viewBox: '0 0 24 24' },
    { name: 'AirplanePaperRight', displayName: 'AirplanePaperRight', icon: <AirplanePaperRight />, viewBox: '0 0 24 24' },
    { name: 'AirplaneRight', displayName: 'AirplaneRight', icon: <AirplaneRight />, viewBox: '0 0 24 24' },
    { name: 'Amber', displayName: 'Amber', icon: <Amber />, viewBox: '0 0 24 24' },
    { name: 'AppIconTSquare', displayName: 'AppIconTSquare', icon: <AppIconTSquare />, viewBox: '0 0 24 24' },
    { name: 'ArrowDown', displayName: 'ArrowDown', icon: <ArrowDown />, viewBox: '0 0 24 24' },
    { name: 'ArrowDownListSortedReverse', displayName: 'ArrowDownListSortedReverse', icon: <ArrowDownListSortedReverse />, viewBox: '0 0 24 24' },
    { name: 'ArrowDownUnderline', displayName: 'ArrowDownUnderline', icon: <ArrowDownUnderline />, viewBox: '0 0 24 24' },
    { name: 'ArrowLeftDownArrowRightUp', displayName: 'ArrowLeftDownArrowRightUp', icon: <ArrowLeftDownArrowRightUp />, viewBox: '0 0 24 24' },
    { name: 'ArrowLeft', displayName: 'ArrowLeft', icon: <ArrowLeft />, viewBox: '0 0 24 24' },
    { name: 'ArrowReturnLeft', displayName: 'ArrowReturnLeft', icon: <ArrowReturnLeft />, viewBox: '0 0 24 24' },
    { name: 'ArrowReturnRight', displayName: 'ArrowReturnRight', icon: <ArrowReturnRight />, viewBox: '0 0 24 24' },
    { name: 'ArrowRight', displayName: 'ArrowRight', icon: <ArrowRight />, viewBox: '0 0 24 24' },
    { name: 'ArrowRightIncomingRectangleVertical', displayName: 'ArrowRightIncomingRectangleVertical', icon: <ArrowRightIncomingRectangleVertical />, viewBox: '0 0 24 24' },
    { name: 'ArrowRightOutgoingRectangleVertical', displayName: 'ArrowRightOutgoingRectangleVertical', icon: <ArrowRightOutgoingRectangleVertical />, viewBox: '0 0 24 24' },
    { name: 'ArrowRightTopOutgoingSquare', displayName: 'ArrowRightTopOutgoingSquare', icon: <ArrowRightTopOutgoingSquare />, viewBox: '0 0 24 24' },
    { name: 'ArrowRightUpArrowLeftDown', displayName: 'ArrowRightUpArrowLeftDown', icon: <ArrowRightUpArrowLeftDown />, viewBox: '0 0 24 24' },
    { name: 'ArrowRotationLeft', displayName: 'ArrowRotationLeft', icon: <ArrowRotationLeft />, viewBox: '0 0 24 24' },
    { name: 'ArrowRotationRight', displayName: 'ArrowRotationRight', icon: <ArrowRotationRight />, viewBox: '0 0 24 24' },
    { name: 'ArrowsCollapse', displayName: 'ArrowsCollapse', icon: <ArrowsCollapse />, viewBox: '0 0 24 24' },
    { name: 'ArrowsDirectionsHorizontalRectangle', displayName: 'ArrowsDirectionsHorizontalRectangle', icon: <ArrowsDirectionsHorizontalRectangle />, viewBox: '0 0 24 24' },
    { name: 'ArrowsDirectionsVertical', displayName: 'ArrowsDirectionsVertical', icon: <ArrowsDirectionsVertical />, viewBox: '0 0 24 24' },
    { name: 'ArrowsExpand', displayName: 'ArrowsExpand', icon: <ArrowsExpand />, viewBox: '0 0 24 24' },
    { name: 'ArrowsRotationLeftDollar', displayName: 'ArrowsRotationLeftDollar', icon: <ArrowsRotationLeftDollar />, viewBox: '0 0 24 24' },
    { name: 'ArrowsRotationLeftFlattened', displayName: 'ArrowsRotationLeftFlattened', icon: <ArrowsRotationLeftFlattened />, viewBox: '0 0 24 24' },
    { name: 'ArrowsRotationLeftRuble', displayName: 'ArrowsRotationLeftRuble', icon: <ArrowsRotationLeftRuble />, viewBox: '0 0 24 24' },
    { name: 'ArrowsRotationRightA', displayName: 'ArrowsRotationRightA', icon: <ArrowsRotationRightA />, viewBox: '0 0 24 24' },
    { name: 'ArrowsRotationRight', displayName: 'ArrowsRotationRight', icon: <ArrowsRotationRight />, viewBox: '0 0 24 24' },
    { name: 'ArrowsRotationRightT', displayName: 'ArrowsRotationRightT', icon: <ArrowsRotationRightT />, viewBox: '0 0 24 24' },
    { name: 'ArrowsRotationRightYuan', displayName: 'ArrowsRotationRightYuan', icon: <ArrowsRotationRightYuan />, viewBox: '0 0 24 24' },
    { name: 'ArrowsShuffleRight', displayName: 'ArrowsShuffleRight', icon: <ArrowsShuffleRight />, viewBox: '0 0 24 24' },
    { name: 'ArrowTurnDownRight', displayName: 'ArrowTurnDownRight', icon: <ArrowTurnDownRight />, viewBox: '0 0 24 24' },
    { name: 'ArrowTurnLeftDown', displayName: 'ArrowTurnLeftDown', icon: <ArrowTurnLeftDown />, viewBox: '0 0 24 24' },
    { name: 'ArrowUpArrowDown', displayName: 'ArrowUpArrowDown', icon: <ArrowUpArrowDown />, viewBox: '0 0 24 24' },
    { name: 'ArrowUp', displayName: 'ArrowUp', icon: <ArrowUp />, viewBox: '0 0 24 24' },
    { name: 'ArrowUpIncomingRectangleHorizontal', displayName: 'ArrowUpIncomingRectangleHorizontal', icon: <ArrowUpIncomingRectangleHorizontal />, viewBox: '0 0 24 24' },
    { name: 'ArrowUpListSorted', displayName: 'ArrowUpListSorted', icon: <ArrowUpListSorted />, viewBox: '0 0 24 24' },
    { name: 'ArrowUpUnderline', displayName: 'ArrowUpUnderline', icon: <ArrowUpUnderline />, viewBox: '0 0 24 24' },
    { name: 'BadgeListShortReverseCenter', displayName: 'BadgeListShortReverseCenter', icon: <BadgeListShortReverseCenter />, viewBox: '0 0 24 24' },
    { name: 'BadgeRibbon', displayName: 'BadgeRibbon', icon: <BadgeRibbon />, viewBox: '0 0 24 24' },
    { name: 'BadgeRoundedPercent', displayName: 'BadgeRoundedPercent', icon: <BadgeRoundedPercent />, viewBox: '0 0 24 24' },
    { name: 'BagPercent', displayName: 'BagPercent', icon: <BagPercent />, viewBox: '0 0 24 24' },
    { name: 'Barcode', displayName: 'Barcode', icon: <Barcode />, viewBox: '0 0 24 24' },
    { name: 'BellCrossedOut', displayName: 'BellCrossedOut', icon: <BellCrossedOut />, viewBox: '0 0 24 24' },
    { name: 'Bell', displayName: 'Bell', icon: <Bell />, viewBox: '0 0 24 24' },
    { name: 'Book', displayName: 'Book', icon: <Book />, viewBox: '0 0 24 24' },
    { name: 'BookmarkCrossedOut', displayName: 'BookmarkCrossedOut', icon: <BookmarkCrossedOut />, viewBox: '0 0 24 24' },
    { name: 'Bookmark', displayName: 'Bookmark', icon: <Bookmark />, viewBox: '0 0 24 24' },
    { name: 'Bookmarks', displayName: 'Bookmarks', icon: <Bookmarks />, viewBox: '0 0 24 24' },
    { name: 'BookShadow', displayName: 'BookShadow', icon: <BookShadow />, viewBox: '0 0 24 24' },
    { name: 'BottleBaby', displayName: 'BottleBaby', icon: <BottleBaby />, viewBox: '0 0 24 24' },
    { name: 'BoxArrowUp', displayName: 'BoxArrowUp', icon: <BoxArrowUp />, viewBox: '0 0 24 24' },
    { name: 'Box', displayName: 'Box', icon: <Box />, viewBox: '0 0 24 24' },
    { name: 'BoxPartition', displayName: 'BoxPartition', icon: <BoxPartition />, viewBox: '0 0 24 24' },
    { name: 'Broom', displayName: 'Broom', icon: <Broom />, viewBox: '0 0 24 24' },
    { name: 'BubbleListShort', displayName: 'BubbleListShort', icon: <BubbleListShort />, viewBox: '0 0 24 24' },
    { name: 'BubblesRounded', displayName: 'BubblesRounded', icon: <BubblesRounded />, viewBox: '0 0 24 24' },
    { name: 'BuildingBank', displayName: 'BuildingBank', icon: <BuildingBank />, viewBox: '0 0 24 24' },
    { name: 'BuildingGovernment', displayName: 'BuildingGovernment', icon: <BuildingGovernment />, viewBox: '0 0 24 24' },
    { name: 'CalendarAcsA', displayName: 'CalendarAcsA', icon: <CalendarAcsA />, viewBox: '0 0 24 24' },
    { name: 'CalendarAcsArrowRotationRight', displayName: 'CalendarAcsArrowRotationRight', icon: <CalendarAcsArrowRotationRight />, viewBox: '0 0 24 24' },
    { name: 'Calendar', displayName: 'Calendar', icon: <Calendar />, viewBox: '0 0 24 24' },
    { name: 'CardAcsArrowLeftIncoming', displayName: 'CardAcsArrowLeftIncoming', icon: <CardAcsArrowLeftIncoming />, viewBox: '0 0 24 24' },
    { name: 'CardAcsArrowRightIncoming', displayName: 'CardAcsArrowRightIncoming', icon: <CardAcsArrowRightIncoming />, viewBox: '0 0 24 24' },
    { name: 'CardAcsArrowRightOutgoing', displayName: 'CardAcsArrowRightOutgoing', icon: <CardAcsArrowRightOutgoing />, viewBox: '0 0 24 24' },
    { name: 'CardAcsCross', displayName: 'CardAcsCross', icon: <CardAcsCross />, viewBox: '0 0 24 24' },
    { name: 'CardAcsPlus', displayName: 'CardAcsPlus', icon: <CardAcsPlus />, viewBox: '0 0 24 24' },
    { name: 'CardCrossedOut', displayName: 'CardCrossedOut', icon: <CardCrossedOut />, viewBox: '0 0 24 24' },
    { name: 'Card', displayName: 'Card', icon: <Card />, viewBox: '0 0 24 24' },
    { name: 'Cards', displayName: 'Cards', icon: <Cards />, viewBox: '0 0 24 24' },
    { name: 'Car', displayName: 'Car', icon: <Car />, viewBox: '0 0 24 24' },
    { name: 'Chain', displayName: 'Chain', icon: <Chain />, viewBox: '0 0 24 24' },
    { name: 'ChartBar', displayName: 'ChartBar', icon: <ChartBar />, viewBox: '0 0 24 24' },
    { name: 'ChartSector', displayName: 'ChartSector', icon: <ChartSector />, viewBox: '0 0 24 24' },
    { name: 'ChatGPT', displayName: 'ChatGPT', icon: <ChatGPT />, viewBox: '0 0 24 24' },
    { name: 'Checkmarks', displayName: 'Checkmarks', icon: <Checkmarks />, viewBox: '0 0 24 24' },
    { name: 'ChevronDown', displayName: 'ChevronDown', icon: <ChevronDown />, viewBox: '0 0 24 24' },
    { name: 'ChevronLeft', displayName: 'ChevronLeft', icon: <ChevronLeft />, viewBox: '0 0 24 24' },
    { name: 'ChevronRight', displayName: 'ChevronRight', icon: <ChevronRight />, viewBox: '0 0 24 24' },
    { name: 'ChevronsLeft', displayName: 'ChevronsLeft', icon: <ChevronsLeft />, viewBox: '0 0 24 24' },
    { name: 'ChevronsRight', displayName: 'ChevronsRight', icon: <ChevronsRight />, viewBox: '0 0 24 24' },
    { name: 'ChevronUp', displayName: 'ChevronUp', icon: <ChevronUp />, viewBox: '0 0 24 24' },
    { name: 'Clip', displayName: 'Clip', icon: <Clip />, viewBox: '0 0 24 24' },
    { name: 'CloudArrowDownOutgoing', displayName: 'CloudArrowDownOutgoing', icon: <CloudArrowDownOutgoing />, viewBox: '0 0 24 24' },
    { name: 'Cloud', displayName: 'Cloud', icon: <Cloud />, viewBox: '0 0 24 24' },
    { name: 'CoinsDollar', displayName: 'CoinsDollar', icon: <CoinsDollar />, viewBox: '0 0 24 24' },
    { name: 'CoinsEuro', displayName: 'CoinsEuro', icon: <CoinsEuro />, viewBox: '0 0 24 24' },
    { name: 'CoinsPlane', displayName: 'CoinsPlane', icon: <CoinsPlane />, viewBox: '0 0 24 24' },
    { name: 'CoinsRuble', displayName: 'CoinsRuble', icon: <CoinsRuble />, viewBox: '0 0 24 24' },
    { name: 'CoinsYuan', displayName: 'CoinsYuan', icon: <CoinsYuan />, viewBox: '0 0 24 24' },
    { name: 'ColorPalette', displayName: 'ColorPalette', icon: <ColorPalette />, viewBox: '0 0 24 24' },
    { name: 'Compass', displayName: 'Compass', icon: <Compass />, viewBox: '0 0 24 24' },
    { name: 'Component', displayName: 'Component', icon: <Component />, viewBox: '0 0 24 24' },
    { name: 'ConnectionArrowsRepeatLeft', displayName: 'ConnectionArrowsRepeatLeft', icon: <ConnectionArrowsRepeatLeft />, viewBox: '0 0 24 24' },
    { name: 'ConnectionArrowTurnLeftDownA', displayName: 'ConnectionArrowTurnLeftDownA', icon: <ConnectionArrowTurnLeftDownA />, viewBox: '0 0 24 24' },
    { name: 'ConnectionArrowTurnRightUpA', displayName: 'ConnectionArrowTurnRightUpA', icon: <ConnectionArrowTurnRightUpA />, viewBox: '0 0 24 24' },
    { name: 'CornerRounded', displayName: 'CornerRounded', icon: <CornerRounded />, viewBox: '0 0 24 24' },
    { name: 'Corners', displayName: 'Corners', icon: <Corners />, viewBox: '0 0 24 24' },
    { name: 'CornersLine', displayName: 'CornersLine', icon: <CornersLine />, viewBox: '0 0 24 24' },
    { name: 'Cross', displayName: 'Cross', icon: <Cross />, viewBox: '0 0 24 24' },
    { name: 'CryptoPro', displayName: 'CryptoPro', icon: <CryptoPro />, viewBox: '0 0 24 24' },
    { name: 'DocumentBookList', displayName: 'DocumentBookList', icon: <DocumentBookList />, viewBox: '0 0 24 24' },
    { name: 'DocumentListAcsArrowDownOutgoing', displayName: 'DocumentListAcsArrowDownOutgoing', icon: <DocumentListAcsArrowDownOutgoing />, viewBox: '0 0 24 24' },
    { name: 'DocumentListAcsArrowRightOutgoing', displayName: 'DocumentListAcsArrowRightOutgoing', icon: <DocumentListAcsArrowRightOutgoing />, viewBox: '0 0 24 24' },
    { name: 'DocumentListAcsArrowRotationRight', displayName: 'DocumentListAcsArrowRotationRight', icon: <DocumentListAcsArrowRotationRight />, viewBox: '0 0 24 24' },
    { name: 'DocumentListAcsCross', displayName: 'DocumentListAcsCross', icon: <DocumentListAcsCross />, viewBox: '0 0 24 24' },
    { name: 'DocumentListAcsMagnifier', displayName: 'DocumentListAcsMagnifier', icon: <DocumentListAcsMagnifier />, viewBox: '0 0 24 24' },
    { name: 'DocumentListAcsPlus', displayName: 'DocumentListAcsPlus', icon: <DocumentListAcsPlus />, viewBox: '0 0 24 24' },
    { name: 'DocumentListAcsShield', displayName: 'DocumentListAcsShield', icon: <DocumentListAcsShield />, viewBox: '0 0 24 24' },
    { name: 'DocumentListAcsStar', displayName: 'DocumentListAcsStar', icon: <DocumentListAcsStar />, viewBox: '0 0 24 24' },
    { name: 'DocumentListBulletedAcsArrowRightIncoming', displayName: 'DocumentListBulletedAcsArrowRightIncoming', icon: <DocumentListBulletedAcsArrowRightIncoming />, viewBox: '0 0 24 24' },
    { name: 'DocumentListBulletedAcsCross', displayName: 'DocumentListBulletedAcsCross', icon: <DocumentListBulletedAcsCross />, viewBox: '0 0 24 24' },
    { name: 'DocumentListBulletedAcsPlus', displayName: 'DocumentListBulletedAcsPlus', icon: <DocumentListBulletedAcsPlus />, viewBox: '0 0 24 24' },
    { name: 'DocumentListBulleted', displayName: 'DocumentListBulleted', icon: <DocumentListBulleted />, viewBox: '0 0 24 24' },
    { name: 'DocumentList', displayName: 'DocumentList', icon: <DocumentList />, viewBox: '0 0 24 24' },
    { name: 'DocumentListMedicine', displayName: 'DocumentListMedicine', icon: <DocumentListMedicine />, viewBox: '0 0 24 24' },
    { name: 'DocumentLosses', displayName: 'DocumentLosses', icon: <DocumentLosses />, viewBox: '0 0 24 24' },
    { name: 'DocumentPatent', displayName: 'DocumentPatent', icon: <DocumentPatent />, viewBox: '0 0 24 24' },
    { name: 'DocumentPercentAcsWatch', displayName: 'DocumentPercentAcsWatch', icon: <DocumentPercentAcsWatch />, viewBox: '0 0 24 24' },
    { name: 'DocumentProfile', displayName: 'DocumentProfile', icon: <DocumentProfile />, viewBox: '0 0 24 24' },
    { name: 'DocumentReportAcsArrowRightOutgoing', displayName: 'DocumentReportAcsArrowRightOutgoing', icon: <DocumentReportAcsArrowRightOutgoing />, viewBox: '0 0 24 24' },
    { name: 'DocumentReportAcsPlus', displayName: 'DocumentReportAcsPlus', icon: <DocumentReportAcsPlus />, viewBox: '0 0 24 24' },
    { name: 'DocumentReport', displayName: 'DocumentReport', icon: <DocumentReport />, viewBox: '0 0 24 24' },
    { name: 'Done', displayName: 'Done', icon: <Done />, viewBox: '0 0 24 24' },
    { name: 'DotsThreeHorizontalArrowDownOutgoing', displayName: 'DotsThreeHorizontalArrowDownOutgoing', icon: <DotsThreeHorizontalArrowDownOutgoing />, viewBox: '0 0 24 24' },
    { name: 'DotsThreeHorizontal', displayName: 'DotsThreeHorizontal', icon: <DotsThreeHorizontal />, viewBox: '0 0 24 24' },
    { name: 'DotsThreeVertical', displayName: 'DotsThreeVertical', icon: <DotsThreeVertical />, viewBox: '0 0 24 24' },
    { name: 'DropPlus', displayName: 'DropPlus', icon: <DropPlus />, viewBox: '0 0 24 24' },
    { name: 'Earth', displayName: 'Earth', icon: <Earth />, viewBox: '0 0 24 24' },
    { name: 'EmblemCross', displayName: 'EmblemCross', icon: <EmblemCross />, viewBox: '0 0 24 24' },
    { name: 'EmblemListShortCenter', displayName: 'EmblemListShortCenter', icon: <EmblemListShortCenter />, viewBox: '0 0 24 24' },
    { name: 'EmblemPercent', displayName: 'EmblemPercent', icon: <EmblemPercent />, viewBox: '0 0 24 24' },
    { name: 'EmblemProfile', displayName: 'EmblemProfile', icon: <EmblemProfile />, viewBox: '0 0 24 24' },
    { name: 'EmblemTAcsCross', displayName: 'EmblemTAcsCross', icon: <EmblemTAcsCross />, viewBox: '0 0 24 24' },
    { name: 'EmblemT', displayName: 'EmblemT', icon: <EmblemT />, viewBox: '0 0 24 24' },
    { name: 'Envelope', displayName: 'Envelope', icon: <Envelope />, viewBox: '0 0 24 24' },
    { name: 'Exit', displayName: 'Exit', icon: <Exit />, viewBox: '0 0 24 24' },
    { name: 'EyeAcsPlus', displayName: 'EyeAcsPlus', icon: <EyeAcsPlus />, viewBox: '0 0 24 24' },
    { name: 'EyeClosed', displayName: 'EyeClosed', icon: <EyeClosed />, viewBox: '0 0 24 24' },
    { name: 'Eye', displayName: 'Eye', icon: <Eye />, viewBox: '0 0 24 24' },
    { name: 'FaceAuthentication', displayName: 'FaceAuthentication', icon: <FaceAuthentication />, viewBox: '0 0 24 24' },
    { name: 'FaceHappy', displayName: 'FaceHappy', icon: <FaceHappy />, viewBox: '0 0 24 24' },
    { name: 'FaceNeutral', displayName: 'FaceNeutral', icon: <FaceNeutral />, viewBox: '0 0 24 24' },
    { name: 'FaceNeutralSquare', displayName: 'FaceNeutralSquare', icon: <FaceNeutralSquare />, viewBox: '0 0 24 24' },
    { name: 'FaceUnhappy', displayName: 'FaceUnhappy', icon: <FaceUnhappy />, viewBox: '0 0 24 24' },
    { name: 'FAQQuestion', displayName: 'FAQQuestion', icon: <FAQQuestion />, viewBox: '0 0 24 24' },
    { name: 'FileAcsArrowLeftOutgoing', displayName: 'FileAcsArrowLeftOutgoing', icon: <FileAcsArrowLeftOutgoing />, viewBox: '0 0 24 24' },
    { name: 'FileAcsCoins', displayName: 'FileAcsCoins', icon: <FileAcsCoins />, viewBox: '0 0 24 24' },
    { name: 'FileAcsHouse', displayName: 'FileAcsHouse', icon: <FileAcsHouse />, viewBox: '0 0 24 24' },
    { name: 'FileAcsMagnifier', displayName: 'FileAcsMagnifier', icon: <FileAcsMagnifier />, viewBox: '0 0 24 24' },
    { name: 'FileAcsPencil', displayName: 'FileAcsPencil', icon: <FileAcsPencil />, viewBox: '0 0 24 24' },
    { name: 'FileAcsPen', displayName: 'FileAcsPen', icon: <FileAcsPen />, viewBox: '0 0 24 24' },
    { name: 'FileAcsPlus', displayName: 'FileAcsPlus', icon: <FileAcsPlus />, viewBox: '0 0 24 24' },
    { name: 'FileAnalysis', displayName: 'FileAnalysis', icon: <FileAnalysis />, viewBox: '0 0 24 24' },
    { name: 'FileArrowReturnUp', displayName: 'FileArrowReturnUp', icon: <FileArrowReturnUp />, viewBox: '0 0 24 24' },
    { name: 'FileElasticBand', displayName: 'FileElasticBand', icon: <FileElasticBand />, viewBox: '0 0 24 24' },
    { name: 'File', displayName: 'File', icon: <File />, viewBox: '0 0 24 24' },
    { name: 'FileListShortReverseAcsArrowRightOutgoing', displayName: 'FileListShortReverseAcsArrowRightOutgoing', icon: <FileListShortReverseAcsArrowRightOutgoing />, viewBox: '0 0 24 24' },
    { name: 'FileListShortReverseAcsCalendar', displayName: 'FileListShortReverseAcsCalendar', icon: <FileListShortReverseAcsCalendar />, viewBox: '0 0 24 24' },
    { name: 'FileListShortReverseAcsChartBar', displayName: 'FileListShortReverseAcsChartBar', icon: <FileListShortReverseAcsChartBar />, viewBox: '0 0 24 24' },
    { name: 'FileListShortReverseAcsCoinsPlane', displayName: 'FileListShortReverseAcsCoinsPlane', icon: <FileListShortReverseAcsCoinsPlane />, viewBox: '0 0 24 24' },
    { name: 'FileListShortReverseAcsCross', displayName: 'FileListShortReverseAcsCross', icon: <FileListShortReverseAcsCross />, viewBox: '0 0 24 24' },
    { name: 'FileListShortReverseAcsLock', displayName: 'FileListShortReverseAcsLock', icon: <FileListShortReverseAcsLock />, viewBox: '0 0 24 24' },
    { name: 'FileListShortReverseAcsPencil', displayName: 'FileListShortReverseAcsPencil', icon: <FileListShortReverseAcsPencil />, viewBox: '0 0 24 24' },
    { name: 'FileListShortReverseAcsPercent', displayName: 'FileListShortReverseAcsPercent', icon: <FileListShortReverseAcsPercent />, viewBox: '0 0 24 24' },
    { name: 'FileListShortReverseAcsWatch', displayName: 'FileListShortReverseAcsWatch', icon: <FileListShortReverseAcsWatch />, viewBox: '0 0 24 24' },
    { name: 'FileListShortReverseAcsYuan', displayName: 'FileListShortReverseAcsYuan', icon: <FileListShortReverseAcsYuan />, viewBox: '0 0 24 24' },
    { name: 'FileListShortReverse', displayName: 'FileListShortReverse', icon: <FileListShortReverse />, viewBox: '0 0 24 24' },
    { name: 'FileListShortReverseMapAcsPin', displayName: 'FileListShortReverseMapAcsPin', icon: <FileListShortReverseMapAcsPin />, viewBox: '0 0 24 24' },
    { name: 'FileOdinS', displayName: 'FileOdinS', icon: <FileOdinS />, viewBox: '0 0 24 24' },
    { name: 'Filters', displayName: 'Filters', icon: <Filters />, viewBox: '0 0 24 24' },
    { name: 'Fingerprint', displayName: 'Fingerprint', icon: <Fingerprint />, viewBox: '0 0 24 24' },
    { name: 'Flag', displayName: 'Flag', icon: <Flag />, viewBox: '0 0 24 24' },
    { name: 'Gavel', displayName: 'Gavel', icon: <Gavel />, viewBox: '0 0 24 24' },
    { name: 'Gear', displayName: 'Gear', icon: <Gear />, viewBox: '0 0 24 24' },
    { name: 'Gift', displayName: 'Gift', icon: <Gift />, viewBox: '0 0 24 24' },
    { name: 'Globe', displayName: 'Globe', icon: <Globe />, viewBox: '0 0 24 24' },
    { name: 'Goblet', displayName: 'Goblet', icon: <Goblet />, viewBox: '0 0 24 24' },
    { name: 'Hand', displayName: 'Hand', icon: <Hand />, viewBox: '0 0 24 24' },
    { name: 'HatGlasses', displayName: 'HatGlasses', icon: <HatGlasses />, viewBox: '0 0 24 24' },
    { name: 'Headphones', displayName: 'Headphones', icon: <Headphones />, viewBox: '0 0 24 24' },
    { name: 'Heart', displayName: 'Heart', icon: <Heart />, viewBox: '0 0 24 24' },
    { name: 'HeartPulse', displayName: 'HeartPulse', icon: <HeartPulse />, viewBox: '0 0 24 24' },
    { name: 'HeartT', displayName: 'HeartT', icon: <HeartT />, viewBox: '0 0 24 24' },
    { name: 'House', displayName: 'House', icon: <House />, viewBox: '0 0 24 24' },
    { name: 'HousePercentCrossedOut', displayName: 'HousePercentCrossedOut', icon: <HousePercentCrossedOut />, viewBox: '0 0 24 24' },
    { name: 'HousePercent', displayName: 'HousePercent', icon: <HousePercent />, viewBox: '0 0 24 24' },
    { name: 'Integration', displayName: 'Integration', icon: <Integration />, viewBox: '0 0 24 24' },
    { name: 'KeyAcsWatch', displayName: 'KeyAcsWatch', icon: <KeyAcsWatch />, viewBox: '0 0 24 24' },
    { name: 'KeyboardKeyBackspaceCross', displayName: 'KeyboardKeyBackspaceCross', icon: <KeyboardKeyBackspaceCross />, viewBox: '0 0 24 24' },
    { name: 'KeyboardKeyT', displayName: 'KeyboardKeyT', icon: <KeyboardKeyT />, viewBox: '0 0 24 24' },
    { name: 'Key', displayName: 'Key', icon: <Key />, viewBox: '0 0 24 24' },
    { name: 'Kiosk', displayName: 'Kiosk', icon: <Kiosk />, viewBox: '0 0 24 24' },
    { name: 'LaptopAcsPhone', displayName: 'LaptopAcsPhone', icon: <LaptopAcsPhone />, viewBox: '0 0 24 24' },
    { name: 'Laptop', displayName: 'Laptop', icon: <Laptop />, viewBox: '0 0 24 24' },
    { name: 'LaptopT', displayName: 'LaptopT', icon: <LaptopT />, viewBox: '0 0 24 24' },
    { name: 'LayerOnLayerRectangleVerticalAngled', displayName: 'LayerOnLayerRectangleVerticalAngled', icon: <LayerOnLayerRectangleVerticalAngled />, viewBox: '0 0 24 24' },
    { name: 'LayerOnLayerRectangleVertical', displayName: 'LayerOnLayerRectangleVertical', icon: <LayerOnLayerRectangleVertical />, viewBox: '0 0 24 24' },
    { name: 'LayoutGrid', displayName: 'LayoutGrid', icon: <LayoutGrid />, viewBox: '0 0 24 24' },
    { name: 'LayoutRowsTwo', displayName: 'LayoutRowsTwo', icon: <LayoutRowsTwo />, viewBox: '0 0 24 24' },
    { name: 'LayoutSquaresFour', displayName: 'LayoutSquaresFour', icon: <LayoutSquaresFour />, viewBox: '0 0 24 24' },
    { name: 'LayoutSquaresFourRhombusOne', displayName: 'LayoutSquaresFourRhombusOne', icon: <LayoutSquaresFourRhombusOne />, viewBox: '0 0 24 24' },
    { name: 'LayoutStackVerticalRounded', displayName: 'LayoutStackVerticalRounded', icon: <LayoutStackVerticalRounded />, viewBox: '0 0 24 24' },
    { name: 'LetterAAcsStarShine', displayName: 'LetterAAcsStarShine', icon: <LetterAAcsStarShine />, viewBox: '0 0 24 24' },
    { name: 'LetterACursor', displayName: 'LetterACursor', icon: <LetterACursor />, viewBox: '0 0 24 24' },
    { name: 'LetterB', displayName: 'LetterB', icon: <LetterB />, viewBox: '0 0 24 24' },
    { name: 'LetterBRusAcsStarShine', displayName: 'LetterBRusAcsStarShine', icon: <LetterBRusAcsStarShine />, viewBox: '0 0 24 24' },
    { name: 'LetterIItalic', displayName: 'LetterIItalic', icon: <LetterIItalic />, viewBox: '0 0 24 24' },
    { name: 'LettersAAUnderline', displayName: 'LettersAAUnderline', icon: <LettersAAUnderline />, viewBox: '0 0 24 24' },
    { name: 'LetterSCrossedOut', displayName: 'LetterSCrossedOut', icon: <LetterSCrossedOut />, viewBox: '0 0 24 24' },
    { name: 'LettersHieroglyphA', displayName: 'LettersHieroglyphA', icon: <LettersHieroglyphA />, viewBox: '0 0 24 24' },
    { name: 'LetterUUnderline', displayName: 'LetterUUnderline', icon: <LetterUUnderline />, viewBox: '0 0 24 24' },
    { name: 'LetterY', displayName: 'LetterY', icon: <LetterY />, viewBox: '0 0 24 24' },
    { name: 'LightBulb', displayName: 'LightBulb', icon: <LightBulb />, viewBox: '0 0 24 24' },
    { name: 'Lightning', displayName: 'Lightning', icon: <Lightning />, viewBox: '0 0 24 24' },
    { name: 'LinesThreeHorizontal', displayName: 'LinesThreeHorizontal', icon: <LinesThreeHorizontal />, viewBox: '0 0 24 24' },
    { name: 'ListBulleted', displayName: 'ListBulleted', icon: <ListBulleted />, viewBox: '0 0 24 24' },
    { name: 'ListBulletedMultiline', displayName: 'ListBulletedMultiline', icon: <ListBulletedMultiline />, viewBox: '0 0 24 24' },
    { name: 'ListChecked', displayName: 'ListChecked', icon: <ListChecked />, viewBox: '0 0 24 24' },
    { name: 'ListNumberedOneTwo', displayName: 'ListNumberedOneTwo', icon: <ListNumberedOneTwo />, viewBox: '0 0 24 24' },
    { name: 'ListSortedCenter', displayName: 'ListSortedCenter', icon: <ListSortedCenter />, viewBox: '0 0 24 24' },
    { name: 'ListSortedReverseCenter', displayName: 'ListSortedReverseCenter', icon: <ListSortedReverseCenter />, viewBox: '0 0 24 24' },
    { name: 'ListUnchecked', displayName: 'ListUnchecked', icon: <ListUnchecked />, viewBox: '0 0 24 24' },
    { name: 'Lock', displayName: 'Lock', icon: <Lock />, viewBox: '0 0 24 24' },
    { name: 'LockOpen', displayName: 'LockOpen', icon: <LockOpen />, viewBox: '0 0 24 24' },
    { name: 'MagicStick', displayName: 'MagicStick', icon: <MagicStick />, viewBox: '0 0 24 24' },
    { name: 'Magnifier', displayName: 'Magnifier', icon: <Magnifier />, viewBox: '0 0 24 24' },
    { name: 'MagnifierPlus', displayName: 'MagnifierPlus', icon: <MagnifierPlus />, viewBox: '0 0 24 24' },
    { name: 'MailDog', displayName: 'MailDog', icon: <MailDog />, viewBox: '0 0 24 24' },
    { name: 'MapCurrentLocation', displayName: 'MapCurrentLocation', icon: <MapCurrentLocation />, viewBox: '0 0 24 24' },
    { name: 'Map', displayName: 'Map', icon: <Map />, viewBox: '0 0 24 24' },
    { name: 'MapPin', displayName: 'MapPin', icon: <MapPin />, viewBox: '0 0 24 24' },
    { name: 'Megaphone', displayName: 'Megaphone', icon: <Megaphone />, viewBox: '0 0 24 24' },
    { name: 'Microphone', displayName: 'Microphone', icon: <Microphone />, viewBox: '0 0 24 24' },
    { name: 'MoneyAcceptorArrowDown', displayName: 'MoneyAcceptorArrowDown', icon: <MoneyAcceptorArrowDown />, viewBox: '0 0 24 24' },
    { name: 'MoneyAcceptorArrowUp', displayName: 'MoneyAcceptorArrowUp', icon: <MoneyAcceptorArrowUp />, viewBox: '0 0 24 24' },
    { name: 'Moneybox', displayName: 'Moneybox', icon: <Moneybox />, viewBox: '0 0 24 24' },
    { name: 'MoonStarShine', displayName: 'MoonStarShine', icon: <MoonStarShine />, viewBox: '0 0 24 24' },
    { name: 'Network', displayName: 'Network', icon: <Network />, viewBox: '0 0 24 24' },
    { name: 'Pacifier', displayName: 'Pacifier', icon: <Pacifier />, viewBox: '0 0 24 24' },
    { name: 'Pattern', displayName: 'Pattern', icon: <Pattern />, viewBox: '0 0 24 24' },
    { name: 'Pencil', displayName: 'Pencil', icon: <Pencil />, viewBox: '0 0 24 24' },
    { name: 'Pen', displayName: 'Pen', icon: <Pen />, viewBox: '0 0 24 24' },
    { name: 'Percent', displayName: 'Percent', icon: <Percent />, viewBox: '0 0 24 24' },
    { name: 'PersonAcsArrowRightOutgoing', displayName: 'PersonAcsArrowRightOutgoing', icon: <PersonAcsArrowRightOutgoing />, viewBox: '0 0 24 24' },
    { name: 'PersonAcsChain', displayName: 'PersonAcsChain', icon: <PersonAcsChain />, viewBox: '0 0 24 24' },
    { name: 'PersonAcsCross', displayName: 'PersonAcsCross', icon: <PersonAcsCross />, viewBox: '0 0 24 24' },
    { name: 'PersonAcsHeart', displayName: 'PersonAcsHeart', icon: <PersonAcsHeart />, viewBox: '0 0 24 24' },
    { name: 'PersonAcsMagnifier', displayName: 'PersonAcsMagnifier', icon: <PersonAcsMagnifier />, viewBox: '0 0 24 24' },
    { name: 'PersonAcsOdinS', displayName: 'PersonAcsOdinS', icon: <PersonAcsOdinS />, viewBox: '0 0 24 24' },
    { name: 'PersonAcsPlus', displayName: 'PersonAcsPlus', icon: <PersonAcsPlus />, viewBox: '0 0 24 24' },
    { name: 'PersonAcsQuestion', displayName: 'PersonAcsQuestion', icon: <PersonAcsQuestion />, viewBox: '0 0 24 24' },
    { name: 'PersonAcsRuble', displayName: 'PersonAcsRuble', icon: <PersonAcsRuble />, viewBox: '0 0 24 24' },
    { name: 'PersonAcsStar', displayName: 'PersonAcsStar', icon: <PersonAcsStar />, viewBox: '0 0 24 24' },
    { name: 'Person', displayName: 'Person', icon: <Person />, viewBox: '0 0 24 24' },
    { name: 'PersonLaptop', displayName: 'PersonLaptop', icon: <PersonLaptop />, viewBox: '0 0 24 24' },
    { name: 'PersonMan', displayName: 'PersonMan', icon: <PersonMan />, viewBox: '0 0 24 24' },
    { name: 'PersonMilitary', displayName: 'PersonMilitary', icon: <PersonMilitary />, viewBox: '0 0 24 24' },
    { name: 'PersonWoman', displayName: 'PersonWoman', icon: <PersonWoman />, viewBox: '0 0 24 24' },
    { name: 'PhoneHandsetArrowRightDownIncoming', displayName: 'PhoneHandsetArrowRightDownIncoming', icon: <PhoneHandsetArrowRightDownIncoming />, viewBox: '0 0 24 24' },
    { name: 'PhoneHandsetArrowRightUpOutgoing', displayName: 'PhoneHandsetArrowRightUpOutgoing', icon: <PhoneHandsetArrowRightUpOutgoing />, viewBox: '0 0 24 24' },
    { name: 'PhoneHandset', displayName: 'PhoneHandset', icon: <PhoneHandset />, viewBox: '0 0 24 24' },
    { name: 'PhoneMobile', displayName: 'PhoneMobile', icon: <PhoneMobile />, viewBox: '0 0 24 24' },
    { name: 'Phonendoscope', displayName: 'Phonendoscope', icon: <Phonendoscope />, viewBox: '0 0 24 24' },
    { name: 'PhotoCamera', displayName: 'PhotoCamera', icon: <PhotoCamera />, viewBox: '0 0 24 24' },
    { name: 'Photo', displayName: 'Photo', icon: <Photo />, viewBox: '0 0 24 24' },
    { name: 'PlaySquare', displayName: 'PlaySquare', icon: <PlaySquare />, viewBox: '0 0 24 24' },
    { name: 'Plus', displayName: 'Plus', icon: <Plus />, viewBox: '0 0 24 24' },
    { name: 'PlusSubscriptionSquare', displayName: 'PlusSubscriptionSquare', icon: <PlusSubscriptionSquare />, viewBox: '0 0 24 24' },
    { name: 'PostBox', displayName: 'PostBox', icon: <PostBox />, viewBox: '0 0 24 24' },
    { name: 'PouchT', displayName: 'PouchT', icon: <PouchT />, viewBox: '0 0 24 24' },
    { name: 'Power', displayName: 'Power', icon: <Power />, viewBox: '0 0 24 24' },
    { name: 'Printer', displayName: 'Printer', icon: <Printer />, viewBox: '0 0 24 24' },
    { name: 'Puzzle', displayName: 'Puzzle', icon: <Puzzle />, viewBox: '0 0 24 24' },
    { name: 'QRCodeAcsArrowRightOutgoing', displayName: 'QRCodeAcsArrowRightOutgoing', icon: <QRCodeAcsArrowRightOutgoing />, viewBox: '0 0 24 24' },
    { name: 'QRCode', displayName: 'QRCode', icon: <QRCode />, viewBox: '0 0 24 24' },
    { name: 'ReceiptListShortAcsArrowRightIncoming', displayName: 'ReceiptListShortAcsArrowRightIncoming', icon: <ReceiptListShortAcsArrowRightIncoming />, viewBox: '0 0 24 24' },
    { name: 'ReceiptListShortAcsPlus', displayName: 'ReceiptListShortAcsPlus', icon: <ReceiptListShortAcsPlus />, viewBox: '0 0 24 24' },
    { name: 'ReceiptListShort', displayName: 'ReceiptListShort', icon: <ReceiptListShort />, viewBox: '0 0 24 24' },
    { name: 'RecordSquare', displayName: 'RecordSquare', icon: <RecordSquare />, viewBox: '0 0 24 24' },
    { name: 'RequisitesListShortAcsArrowRightOutgoing', displayName: 'RequisitesListShortAcsArrowRightOutgoing', icon: <RequisitesListShortAcsArrowRightOutgoing />, viewBox: '0 0 24 24' },
    { name: 'RequisitesListShortAcsArrowRotationRight', displayName: 'RequisitesListShortAcsArrowRotationRight', icon: <RequisitesListShortAcsArrowRotationRight />, viewBox: '0 0 24 24' },
    { name: 'RequisitesListShortAcsCross', displayName: 'RequisitesListShortAcsCross', icon: <RequisitesListShortAcsCross />, viewBox: '0 0 24 24' },
    { name: 'RequisitesListShort', displayName: 'RequisitesListShort', icon: <RequisitesListShort />, viewBox: '0 0 24 24' },
    { name: 'RequisitesT', displayName: 'RequisitesT', icon: <RequisitesT />, viewBox: '0 0 24 24' },
    { name: 'ReviewAcsMagnifier', displayName: 'ReviewAcsMagnifier', icon: <ReviewAcsMagnifier />, viewBox: '0 0 24 24' },
    { name: 'Rocket', displayName: 'Rocket', icon: <Rocket />, viewBox: '0 0 24 24' },
    { name: 'RubleDigital', displayName: 'RubleDigital', icon: <RubleDigital />, viewBox: '0 0 24 24' },
    { name: 'Safe', displayName: 'Safe', icon: <Safe />, viewBox: '0 0 24 24' },
    { name: 'ShareAndroid', displayName: 'ShareAndroid', icon: <ShareAndroid />, viewBox: '0 0 24 24' },
    { name: 'Share', displayName: 'Share', icon: <Share />, viewBox: '0 0 24 24' },
    { name: 'ShieldLock', displayName: 'ShieldLock', icon: <ShieldLock />, viewBox: '0 0 24 24' },
    { name: 'ShieldMagnifier', displayName: 'ShieldMagnifier', icon: <ShieldMagnifier />, viewBox: '0 0 24 24' },
    { name: 'ShieldPercent', displayName: 'ShieldPercent', icon: <ShieldPercent />, viewBox: '0 0 24 24' },
    { name: 'Shop', displayName: 'Shop', icon: <Shop />, viewBox: '0 0 24 24' },
    { name: 'ShoppingBasket', displayName: 'ShoppingBasket', icon: <ShoppingBasket />, viewBox: '0 0 24 24' },
    { name: 'SidebarChevronLeft', displayName: 'SidebarChevronLeft', icon: <SidebarChevronLeft />, viewBox: '0 0 24 24' },
    { name: 'SidebarChevronRight', displayName: 'SidebarChevronRight', icon: <SidebarChevronRight />, viewBox: '0 0 24 24' },
    { name: 'SignalHorizontal', displayName: 'SignalHorizontal', icon: <SignalHorizontal />, viewBox: '0 0 24 24' },
    { name: 'SignalVertical', displayName: 'SignalVertical', icon: <SignalVertical />, viewBox: '0 0 24 24' },
    { name: 'Snowflake', displayName: 'Snowflake', icon: <Snowflake />, viewBox: '0 0 24 24' },
    { name: 'Spacing', displayName: 'Spacing', icon: <Spacing />, viewBox: '0 0 24 24' },
    { name: 'SpeedometerAcsCross', displayName: 'SpeedometerAcsCross', icon: <SpeedometerAcsCross />, viewBox: '0 0 24 24' },
    { name: 'Speedometer', displayName: 'Speedometer', icon: <Speedometer />, viewBox: '0 0 24 24' },
    { name: 'Spravochnaya', displayName: 'Spravochnaya', icon: <Spravochnaya />, viewBox: '0 0 24 24' },
    { name: 'StarCrossedOut', displayName: 'StarCrossedOut', icon: <StarCrossedOut />, viewBox: '0 0 24 24' },
    { name: 'Star', displayName: 'Star', icon: <Star />, viewBox: '0 0 24 24' },
    { name: 'SuitcaseAcsPlus', displayName: 'SuitcaseAcsPlus', icon: <SuitcaseAcsPlus />, viewBox: '0 0 24 24' },
    { name: 'Suitcase', displayName: 'Suitcase', icon: <Suitcase />, viewBox: '0 0 24 24' },
    { name: 'Sun', displayName: 'Sun', icon: <Sun />, viewBox: '0 0 24 24' },
    { name: 'Tag', displayName: 'Tag', icon: <Tag />, viewBox: '0 0 24 24' },
    { name: 'TargetDarts', displayName: 'TargetDarts', icon: <TargetDarts />, viewBox: '0 0 24 24' },
    { name: 'Telegram', displayName: 'Telegram', icon: <Telegram />, viewBox: '0 0 24 24' },
    { name: 'ThumbDown', displayName: 'ThumbDown', icon: <ThumbDown />, viewBox: '0 0 24 24' },
    { name: 'ThumbUp', displayName: 'ThumbUp', icon: <ThumbUp />, viewBox: '0 0 24 24' },
    { name: 'Trash', displayName: 'Trash', icon: <Trash />, viewBox: '0 0 24 24' },
    { name: 'TruckAcsPlus', displayName: 'TruckAcsPlus', icon: <TruckAcsPlus />, viewBox: '0 0 24 24' },
    { name: 'Truck', displayName: 'Truck', icon: <Truck />, viewBox: '0 0 24 24' },
    { name: 'Umbrella', displayName: 'Umbrella', icon: <Umbrella />, viewBox: '0 0 24 24' },
    { name: 'USBFlashDriveAcsMagnifier', displayName: 'USBFlashDriveAcsMagnifier', icon: <USBFlashDriveAcsMagnifier />, viewBox: '0 0 24 24' },
    { name: 'USBFlashDrive', displayName: 'USBFlashDrive', icon: <USBFlashDrive />, viewBox: '0 0 24 24' },
    { name: 'VectorSector', displayName: 'VectorSector', icon: <VectorSector />, viewBox: '0 0 24 24' },
    { name: 'WalletAcsArrowDownIncoming', displayName: 'WalletAcsArrowDownIncoming', icon: <WalletAcsArrowDownIncoming />, viewBox: '0 0 24 24' },
    { name: 'WalletAcsPlus', displayName: 'WalletAcsPlus', icon: <WalletAcsPlus />, viewBox: '0 0 24 24' },
    { name: 'Wallet', displayName: 'Wallet', icon: <Wallet />, viewBox: '0 0 24 24' },
    { name: 'WarningTriangle', displayName: 'WarningTriangle', icon: <WarningTriangle />, viewBox: '0 0 24 24' },
    { name: 'WatchAcsTwoFour', displayName: 'WatchAcsTwoFour', icon: <WatchAcsTwoFour />, viewBox: '0 0 24 24' },
    { name: 'WatchArrowRotationLeft', displayName: 'WatchArrowRotationLeft', icon: <WatchArrowRotationLeft />, viewBox: '0 0 24 24' },
    { name: 'Watch', displayName: 'Watch', icon: <Watch />, viewBox: '0 0 24 24' },
    { name: 'WatchTimer', displayName: 'WatchTimer', icon: <WatchTimer />, viewBox: '0 0 24 24' },
    { name: 'WhatsApp', displayName: 'WhatsApp', icon: <WhatsApp />, viewBox: '0 0 24 24' },
    { name: 'X', displayName: 'X', icon: <X />, viewBox: '0 0 24 24' },
];

const renderIconGrid = (icons: IconItem[], size: string) => (
    <div className="icons-preview__grid icons-preview__grid--compact">
        {icons.map(item => (
            <div key={item.name} className="icons-preview__card">
                <span className="ds-icon icons-preview__icon" style={{ '--icon-size': size } as React.CSSProperties}>
                    {item.icon}
                </span>
                <p className="icons-preview__label">
                    {item.displayName}
                </p>
            </div>
        ))}
    </div>
);

export const IconsPreview: React.FC = () => {
    return (
        <div className="tab-panel is-active" id="icons-panel">
            {ICON_SIZES.map(sizeGroup => (
                <section key={sizeGroup.label} className="component-screen">
                    <div className="icons-preview__header">
                        <h1 className="component-screen__title ts-600-2xl">{sizeGroup.label}</h1>
                    </div>
                    {sizeGroup.groups.map(group => (
                        <React.Fragment key={group.style}>
                            <p className="ts-500-m" style={{ color: 'var(--primitive-neutral-4)' }}>{group.style}</p>
                            {renderIconGrid(group.icons, sizeGroup.size)}
                        </React.Fragment>
                    ))}
                </section>
            ))}

            <section className="component-screen">
                <div className="icons-preview__header">
                    <h1 className="component-screen__title ts-600-2xl">24px</h1>
                </div>
                <p className="ts-500-m" style={{ color: 'var(--primitive-neutral-4)' }}>Stroked</p>
                {renderIconGrid(NEW_ICONS, '24px')}
            </section>
        </div>
    );
};
